version: '3.0'
services:
  local-rabbtmq:
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mqadmin
      RABBITMQ_DEFAULT_PASS: 1111
    volumes:
      - '~/env/docker/mq-container/volumes/rabbitmq-local:/data/db'
  local-postgres:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: testadmin
      POSTGRES_PASSWORD: 1111
    volumes:
      - '~/env/docker/postgres/volumes/local-postgres:/var/lib/postgresql/data'
